DEST = "./data"
symbols = ["BTCUSDT", "ETHUSDT","SUIUSDT","SOLUSDT"]

# UM only
# allowed: bookDepth, bookTicker, trades, metrics, premiumIndexKlines, indexPriceKlines, klines, aggTrades,
data_types = ["bookDepth","trades",'metrics','premiumIndexKlines','indexPriceKlines', 'klines', "aggTrades"]
# interval for kline related 
interval= "1m"
