DEST = "/mnt/wd16t/crypto-data"
symbols = ["BTCUSDT", "ETHUSDT","SUIUSDT","SOLUSDT"]

# bookDepth, bookTicker, trades, metrics, premiumIndexKlines, indexPriceKlines, klines, aggTrades,
#data_types = ["bookDepth","bookTicker","trades",'metrics','premiumIndexKlines','indexPriceKlines', 'klines','aggTrades']
data_types = ["bookDepth","trades",'metrics','premiumIndexKlines','indexPriceKlines', 'klines', "aggTrades"]
interval= "1m"
